export const SET_CURRENT_VIEW = "SET_CURRENT_VIEW";

// Provider actions
export const FETCH_PROVIDERS_REQUEST = "FETCH_PROVIDERS_REQUEST";
export const FETCH_PROVIDERS_SUCCESS = "FETCH_PROVIDERS_SUCCESS";
export const FETCH_PROVIDERS_FAILURE = "FETCH_PROVIDERS_FAILURE";
