export const SET_CURRENT_VIEW = "SET_CURRENT_VIEW";

// Provider actions
export const FETCH_PROVIDERS_REQUEST = "FETCH_PROVIDERS_REQUEST";
export const FETCH_PROVIDERS_SUCCESS = "FETCH_PROVIDERS_SUCCESS";
export const FETCH_PROVIDERS_FAILURE = "FETCH_PROVIDERS_FAILURE";
export const APPLY_FILTERS_SUCCESS = "APPLY_FILTERS_SUCCESS";

// Filter actions
export const SET_SERVICE_FILTER = "SET_SERVICE_FILTER";
export const SET_TYPE_FILTER = "SET_TYPE_FILTER";
export const SET_CENTER_FILTER = "SET_CENTER_FILTER";
export const APPLY_FILTERS = "APPLY_FILTERS";
export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const SET_APPLIED_FILTERS = "SET_APPLIED_FILTERS";

export const SET_SELECTED_DATE = "SET_SELECTED_DATE";

// Search actions
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const SEARCH_PROVIDERS_REQUEST = "SEARCH_PROVIDERS_REQUEST";
export const SEARCH_PROVIDERS_SUCCESS = "SEARCH_PROVIDERS_SUCCESS";
export const SEARCH_PROVIDERS_FAILURE = "SEARCH_PROVIDERS_FAILURE";
export const ADD_SELECTED_PROVIDER = "ADD_SELECTED_PROVIDER";
export const REMOVE_SELECTED_PROVIDER = "REMOVE_SELECTED_PROVIDER";
export const CLEAR_SELECTED_PROVIDERS = "CLEAR_SELECTED_PROVIDERS";

// Calendar actions
export const SET_CALENDAR_DATE = "SET_CALENDAR_DATE";
export const SET_CALENDAR_VIEW_MODE = "SET_CALENDAR_VIEW_MODE";
export const SET_CALENDAR_DATE_RANGE = "SET_CALENDAR_DATE_RANGE";
